services:
  - type: static
    name: web-cv-fresh
    buildCommand: npm install && npm run build
    publishPath: out
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: 1
